global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files: null
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: ln-bik-mc
  scrape_interval: 5s
  metrics_path: /ops/prometheus
  static_configs:
  - targets:
    - localhost:8092
- job_name: tsm
  scrape_interval: 5s
  metrics_path: /ops/prometheus
  static_configs:
  - targets:
    - localhost:8093
- job_name: node-exporter
  static_configs:
  - targets:
    - localhost:9100
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9008
