{
 "title": "HikariCP (Micrometer.io)",
 "description": "HikariCP Dashboard (Micrometer.io)",
 "tags": [
  "prometheus",
  "hikaricp",
  "micrometer",
  "spring boot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(jdbc_connections_min{application=\"$application\"}, region)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jdbc_connections_min{application=\"$application\", region=\"$region\"}, instance)"
   },
   {
    "name": "hikaricp_pool_name",
    "label": "Hikari  Pool Name",
    "query": "label_values(hikaricp_connections_min{application=\"$application\", region=\"$region\", instance=~\"$instance\"}, pool)"
   },
   {
    "name": "jdbc_connection_name",
    "label": "JDBC Connection Name",
    "query": "label_values(jdbc_connections_min{application=\"$application\", region=\"$region\", instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "hikaricp_connections_active{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "hikaricp_connections_max{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}"
    }
   ]
  },
  {
   "title": "Min",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "hikaricp_connections_min{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}"
    }
   ]
  },
  {
   "title": "Usage Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_usage_seconds_sum{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_usage_seconds_count{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Creation Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_creation_seconds_sum{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_creation_seconds_count{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Creation"
    }
   ]
  },
  {
   "title": "Acquire Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_sum{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_acquire_seconds_count{application=\"$application\", region=\"$region\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Acquire"
    }
   ]
  },
  { "title": "JDBC Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jdbc_connections_min{application=\"$application\", region=\"$region\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jdbc_connections_active{application=\"$application\", region=\"$region\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jdbc_connections_max{application=\"$application\", region=\"$region\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
    }
   ]
  }
 ]
}